-- TABLAS TEMPORALES Y GLOBALES-- Tabla temporal local
/*Las tablas temporales son tablas que las crea el  usuario (desarrollador / programador) temporalmente  para resolver problemas complejos donde se necesita  almacenar la información en un estado intermedio.Hay dos tipos de tablas temporales: Locales y Globales.  Las tablas locales son visibles solamente en la sesión  actual mientras que las globales pueden ser accedidas  desde otra sesión. Las tablas temporales (ambas:  locales y globales) se eliminan automáticamente al  ﬁnalizar la sesión o la función o el procedimiento almacenado en el cual fueron deﬁnidas (creadas).También se pueden eliminar con "Drop table".*/CREATE TABLE #Provincias(ProvinciaID int NOT NULL, Ciudad varchar(40) NOT NULL);
SELECT * FROM #Provincias

-- Tabla temporal global/* Para crear tablas temporales globales se emplea  la misma sintaxis que para crear cualquier tabla,  excepto que se coloca un signo numeral doble  (##) precediendo el nombre.El (o los) numerales son parte del nombre.  Así que puede crearse una tabla permanente  llamada "libros", otra tabla temporal localllamada "#libros" y una tercera tabla temporal  global denominada "##libros".*/

-- Expresión de tabla común (CTE)-- WITH common_table_expression/*Especiﬁca un conjunto de resultados temporal con  nombre, conocido como expresión de tabla común (CTE).  Se deriva de una consulta simple y se deﬁne en el ámbito  de ejecución de una sola instrucción SELECT, INSERT,  UPDATE o DELETE. Esta cláusula también se puede utilizar  en una instrucción CREATE VIEW como parte de la  instrucción SELECT que la deﬁne.*/WITH Sales_CTE (SalesPersonID, SalesOrderID, SalesYear) AS(SELECT SalesPersonID, SalesOrderID, YEAR(OrderDate) AS  SalesYearFROM Sales.SalesOrderHeader  WHERE SalesOrderID=43659)SELECT * FROM Sales_CTE;

-- Bulk Insert /* Select IntoLa instrucción SELECT INTO crea una nueva  tabla y la llena con el conjunto de resultados  de la instrucción SELECT.SELECT INTO se puede emplear para combinar  datos de varias tablas o vistas en una tabla.También se puede utilizar para crear una  nueva tabla que contenga datos seleccionados  de un servidor vinculado.La estructura de la nueva tabla se deﬁne con  los atributos de las expresiones de la lista de  selección.*/SELECT TerritoryID, NameINTO #Territorios FROM Sales.SalesTerritory WHERE CountryRegionCode='US';SELECT * FROM #Territorios  ORDER BY TerritoryID;
